import { Jost, Oswald } from 'next/font/google'
import Script from 'next/script'
import "/public/stylesheets/bootstrap.min.css"
import "/public/stylesheets/bootstrap.rtl.min.css"
import "/public/stylesheets/bootstrap-grid.min.css"
import "/public/stylesheets/bootstrap-reboot.min.css"
import "/public/stylesheets/bootstrap-utilities.rtl.min.css"
import "/public/stylesheets/bootstrap-utilities.min.css"
import "/public/stylesheets/bootstrap-reboot.rtl.min.css"
import "/public/stylesheets/bootstrap-grid.rtl.min.css"
import "/public/stylesheets/style.css"
import "/public/stylesheets/responsive.css"
import "/public/stylesheets/colors/color1.css"
import "/public/stylesheets/owl.carousel.css"
import "/public/stylesheets/animate.css"
import "/public/stylesheets/animate.min.css"
import "/public/stylesheets/swiper-bundle.min.css"
import "/public/stylesheets/magnific-popup.min.css"
import "/public/stylesheets/map.min.css"

const jost = Jost({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--jost',
	display: 'swap',
})
const oswald = Oswald({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--oswald',
	display: 'swap',
})
export const metadata = {
	title: 'Lustre Athletic',
	description: 'Generated by Lustre Athletic',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				{/* Google Tag */}
				<Script
					async
					src="https://www.googletagmanager.com/gtag/js?id=G-5KVRGZ0LP7"
					strategy="afterInteractive"
				/>
				<Script id="google-analytics" strategy="afterInteractive">
					{`
						window.dataLayer = window.dataLayer || [];
						function gtag(){dataLayer.push(arguments);}
						gtag('js', new Date());
						gtag('config', 'G-5KVRGZ0LP7');
					`}
				</Script>

				{/* Meta Pixel */}
				<Script id="meta-pixel" strategy="afterInteractive">
					{`
						!function(f,b,e,v,n,t,s)
						{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
						n.callMethod.apply(n,arguments):n.queue.push(arguments)};
						if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
						n.queue=[];t=b.createElement(e);t.async=!0;
						t.src=v;s=b.getElementsByTagName(e)[0];
						s.parentNode.insertBefore(t,s)}(window, document,'script',
						'https://connect.facebook.net/en_US/fbevents.js');
						fbq('init', '748909144407418');
						fbq('track', 'PageView');
					`}
				</Script>
			</head>
			<body className={`${jost.variable} ${oswald.variable} header-sticky`}>
				{/* Meta Pixel noscript */}
				<noscript>
					<img
						height="1"
						width="1"
						style={{ display: 'none' }}
						src="https://www.facebook.com/tr?id=748909144407418&ev=PageView&noscript=1"
					/>
				</noscript>
				{children}
			</body>
		</html>
	)
}
